# 28 错误处理

panic后会执行所有defer动作，而os.Exit不会。
如果defer的函数调用了recover，panic就会停止，程序将继续运行。
```go
defer func() {
    if e := recover(); e != nil {
        fmt.Println(e)
    }
}()
panic("I forgot my towel")

// I forgot my towel
```


